package com.gulfmobiles.app;

import android.app.*;
import android.os.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.content.*;
import android.database.Cursor;
import android.view.*;
import android.view.inputmethod.InputMethodManager;
import android.widget.*;
import java.text.SimpleDateFormat;
import java.util.*;

public class MainActivity extends Activity {
    DB db; LinearLayout root, content, list; TextView totalSale,totalExpense,totalProfit; SimpleDateFormat df=new SimpleDateFormat("dd MMM yyyy, hh:mm a",Locale.getDefault());
    int navy=Color.rgb(6,43,73), blue=Color.rgb(11,92,173), lime=Color.rgb(154,203,24), bg=Color.rgb(244,247,250), text=Color.rgb(23,50,77), green=Color.rgb(22,138,74), red=Color.rgb(200,60,60);
    int dp(float x){return (int)(x*getResources().getDisplayMetrics().density+.5f);} 
    TextView tv(String s,float size,int color,boolean bold){ TextView t=new TextView(this); t.setText(s); t.setTextSize(size); t.setTextColor(color); t.setTypeface(Typeface.DEFAULT,bold?Typeface.BOLD:Typeface.NORMAL); return t; }
    GradientDrawable bgd(int color,float r){ GradientDrawable g=new GradientDrawable(); g.setColor(color); g.setCornerRadius(dp(r)); return g; }
    TextView card(String label){ TextView t=tv(label,12,Color.DKGRAY,false); return t; }
    @Override public void onCreate(Bundle b){ super.onCreate(b); db=new DB(this); build(); refresh(); }
    void build(){
        root=new LinearLayout(this); root.setOrientation(LinearLayout.VERTICAL); root.setBackgroundColor(bg); setContentView(root);
        LinearLayout bar=new LinearLayout(this); bar.setPadding(dp(18),dp(16),dp(18),dp(14)); bar.setGravity(Gravity.CENTER_VERTICAL); bar.setBackgroundColor(navy);
        TextView logo=tv("G",30,Color.WHITE,true); logo.setGravity(Gravity.CENTER); logo.setBackground(bgd(lime,20)); bar.addView(logo,new LinearLayout.LayoutParams(dp(48),dp(48)));
        LinearLayout names=new LinearLayout(this); names.setOrientation(LinearLayout.VERTICAL); names.setPadding(dp(12),0,0,0);
        TextView n=tv("Gulf Mobiles",22,Color.WHITE,true); names.addView(n); TextView sub=tv("BUS STAND CHERUPUZHA  •  SALES",11,Color.rgb(210,225,238),false); names.addView(sub); bar.addView(names,new LinearLayout.LayoutParams(0,-2,1));
        root.addView(bar,new LinearLayout.LayoutParams(-1,dp(78)));
        ScrollView sv=new ScrollView(this); content=new LinearLayout(this); content.setOrientation(LinearLayout.VERTICAL); content.setPadding(dp(16),dp(16),dp(16),dp(24)); sv.addView(content); root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
        LinearLayout nav=new LinearLayout(this); nav.setPadding(dp(12),dp(8),dp(12),dp(8)); nav.setBackgroundColor(Color.WHITE);
        Button home=btn("Dashboard"); Button add=btn("+ Add Sale"); Button jobs=btn("Job Sheets"); Button records=btn("Sales History"); nav.addView(home,new LinearLayout.LayoutParams(0,dp(50),1)); nav.addView(add,new LinearLayout.LayoutParams(0,dp(50),1)); nav.addView(jobs,new LinearLayout.LayoutParams(0,dp(50),1)); nav.addView(records,new LinearLayout.LayoutParams(0,dp(50),1)); root.addView(nav,new LinearLayout.LayoutParams(-1,dp(66)));
        home.setOnClickListener(v->showDashboard()); add.setOnClickListener(v->addDialog()); jobs.setOnClickListener(v->showJobs()); records.setOnClickListener(v->showRecords());
    }
    Button btn(String s){ Button b=new Button(this); b.setText(s); b.setTextSize(12); b.setTextColor(navy); b.setAllCaps(false); b.setBackground(bgd(Color.WHITE,14)); return b; }
    TextView title(String s){ TextView t=tv(s,22,text,true); t.setPadding(0,dp(4),0,dp(12)); return t; }
    void clear(){ content.removeAllViews(); }
    TextView metric(String label,String value,int valueColor){ LinearLayout box=new LinearLayout(this); box.setOrientation(LinearLayout.VERTICAL); box.setPadding(dp(14),dp(14),dp(10),dp(14)); box.setBackground(bgd(Color.WHITE,18)); TextView l=tv(label,12,Color.rgb(95,110,125),false); TextView v=tv(value,20,valueColor,true); box.addView(l); box.addView(v); return box.getChildAt(1); }
    LinearLayout metricBox(String label,TextView[] out,int idx,int color){ LinearLayout box=new LinearLayout(this); box.setOrientation(LinearLayout.VERTICAL); box.setPadding(dp(14),dp(14),dp(10),dp(14)); box.setBackground(bgd(Color.WHITE,18)); box.addView(tv(label,12,Color.rgb(95,110,125),false)); TextView v=tv("₹ 0",20,color,true); box.addView(v); out[idx]=v; return box; }
    void showDashboard(){ clear(); content.addView(title("Sales Dashboard"));
        TextView[] a=new TextView[3]; LinearLayout row=new LinearLayout(this); row.setWeightSum(3); row.setGravity(Gravity.CENTER); row.addView(metricBox("TOTAL SALE",a,0,blue),new LinearLayout.LayoutParams(0,dp(92),1)); row.addView(metricBox("TOTAL EXPENSE",a,1,red),new LinearLayout.LayoutParams(0,dp(92),1)); row.addView(metricBox("TOTAL PROFIT",a,2,green),new LinearLayout.LayoutParams(0,dp(92),1)); content.addView(row); totalSale=a[0]; totalExpense=a[1]; totalProfit=a[2];
        TextView h=tv("Recent Entries",17,text,true); h.setPadding(0,dp(24),0,dp(10)); content.addView(h); list=new LinearLayout(this); list.setOrientation(LinearLayout.VERTICAL); content.addView(list); loadRecent(5);
    }
    String money(double x){ return "₹ "+String.format(Locale.US,"%,.2f",x); }
    void refresh(){ showDashboard(); }
    void loadRecent(int limit){ Cursor c=db.all(); int i=0; while(c.moveToNext() && i<limit){ addRow(c,true); i++; } c.close(); if(i==0) list.addView(tv("No sales yet. Tap + Add Sale to start.",14,Color.rgb(100,115,130),false)); }
    void addRow(Cursor c,boolean compact){ long id=c.getLong(0); double sale=c.getDouble(1), exp=c.getDouble(2), prof=c.getDouble(4); long time=c.getLong(3); LinearLayout card=new LinearLayout(this); card.setOrientation(LinearLayout.VERTICAL); card.setPadding(dp(14),dp(12),dp(14),dp(12)); card.setBackground(bgd(Color.WHITE,16)); LinearLayout top=new LinearLayout(this); top.setGravity(Gravity.CENTER_VERTICAL); top.addView(tv(df.format(new Date(time)),12,Color.DKGRAY,false),new LinearLayout.LayoutParams(0,-2,1)); TextView p=tv(money(prof),16,prof>=0?green:red,true); top.addView(p); card.addView(top); LinearLayout cols=new LinearLayout(this); cols.setPadding(0,dp(8),0,0); TextView s=tv("Sale\n"+money(sale),13,blue,true); TextView e=tv("Expense\n"+money(exp),13,red,true); TextView pr=tv("Profit\n"+money(prof),13,green,true); cols.addView(s,new LinearLayout.LayoutParams(0,-2,1)); cols.addView(e,new LinearLayout.LayoutParams(0,-2,1)); cols.addView(pr,new LinearLayout.LayoutParams(0,-2,1)); card.addView(cols); card.setOnLongClickListener(v->{ new AlertDialog.Builder(this).setTitle("Delete entry?").setMessage("This sale record will be removed.").setNegativeButton("Cancel",null).setPositiveButton("Delete",(d,w)->{db.delete(id); showRecords();}).show(); return true; }); LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(108)); lp.setMargins(0,0,0,dp(10)); list.addView(card,lp); }
    void showRecords(){ clear(); content.addView(title("Sales History")); TextView note=tv("Long-press an entry to delete it",12,Color.rgb(100,115,130),false); note.setPadding(0,0,0,dp(12)); content.addView(note); list=new LinearLayout(this); list.setOrientation(LinearLayout.VERTICAL); content.addView(list); Cursor c=db.all(); int count=0; while(c.moveToNext()){addRow(c,false);count++;} c.close(); if(count==0) list.addView(tv("No records found.",14,Color.DKGRAY,false)); }
    void showJobs(){ clear(); content.addView(title("Job Sheets")); Button add=btn("+ New Job Sheet"); add.setTextSize(14); add.setTextColor(Color.WHITE); add.setBackground(bgd(blue,14)); LinearLayout.LayoutParams ab=new LinearLayout.LayoutParams(-1,dp(52)); ab.setMargins(0,0,0,dp(12)); content.addView(add,ab); add.setOnClickListener(v->jobDialog()); list=new LinearLayout(this); list.setOrientation(LinearLayout.VERTICAL); content.addView(list); Cursor c=db.jobs(); int count=0; while(c.moveToNext()){addJobRow(c);count++;} c.close(); if(count==0) list.addView(tv("No job sheets yet.",14,Color.DKGRAY,false)); }
    void addJobRow(Cursor c){ long id=c.getLong(0); String customer=c.getString(1), phone=c.getString(2), device=c.getString(3), issue=c.getString(4), status=c.getString(5); double amount=c.getDouble(6); long time=c.getLong(7); LinearLayout card=new LinearLayout(this); card.setOrientation(LinearLayout.VERTICAL); card.setPadding(dp(14),dp(12),dp(14),dp(12)); card.setBackground(bgd(Color.WHITE,16)); LinearLayout top=new LinearLayout(this); top.addView(tv(customer,17,text,true),new LinearLayout.LayoutParams(0,-2,1)); top.addView(tv(status,12,status.equals("Ready")?green:blue,true)); card.addView(top); card.addView(tv(device+"  •  "+(phone==null?"":phone),13,Color.DKGRAY,false)); card.addView(tv("Issue: "+issue,13,Color.rgb(80,95,110),false)); card.addView(tv("Amount: "+money(amount)+"   •   "+df.format(new Date(time)),12,Color.rgb(100,115,130),false)); card.setOnLongClickListener(v->{new AlertDialog.Builder(this).setTitle("Delete job sheet?").setNegativeButton("Cancel",null).setPositiveButton("Delete",(d,w)->{db.deleteJob(id);showJobs();}).show();return true;}); LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(126)); lp.setMargins(0,0,0,dp(10)); list.addView(card,lp); }
    void jobDialog(){ LinearLayout box=new LinearLayout(this); box.setOrientation(LinearLayout.VERTICAL); box.setPadding(dp(20),dp(8),dp(20),0); EditText customer=input("Customer name"); EditText phone=input("Phone number"); EditText device=input("Device / Model"); EditText issue=input("Problem / Complaint"); EditText amount=input("Service amount (₹)"); amount.setInputType(2|8192); Spinner status=new Spinner(this); String[] st={"Received","In Progress","Ready","Delivered"}; status.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,st)); box.addView(customer);box.addView(phone);box.addView(device);box.addView(issue);box.addView(amount);box.addView(status,new LinearLayout.LayoutParams(-1,dp(52))); AlertDialog dlg=new AlertDialog.Builder(this).setTitle("New Job Sheet").setView(box).setNegativeButton("Cancel",null).setPositiveButton("Save",null).create(); dlg.setOnShowListener(x->dlg.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{String cn=customer.getText().toString().trim();if(cn.isEmpty()){customer.setError("Enter customer name");return;}db.addJob(cn,phone.getText().toString().trim(),device.getText().toString().trim(),issue.getText().toString().trim(),status.getSelectedItem().toString(),num(amount));dlg.dismiss();showJobs();}));dlg.show(); }
    EditText input(String hint){ EditText e=new EditText(this);e.setHint(hint);e.setTextSize(15);e.setSingleLine(true);e.setLayoutParams(new LinearLayout.LayoutParams(-1,dp(54)));return e; }
    void addDialog(){ final LinearLayout box=new LinearLayout(this); box.setOrientation(LinearLayout.VERTICAL); box.setPadding(dp(20),dp(8),dp(20),0); EditText sale=new EditText(this); sale.setHint("Sale amount (₹)"); sale.setInputType(2|8192); EditText exp=new EditText(this); exp.setHint("Expense amount (₹)"); exp.setInputType(2|8192); box.addView(sale,new LinearLayout.LayoutParams(-1,dp(58))); box.addView(exp,new LinearLayout.LayoutParams(-1,dp(58))); TextView preview=tv("Profit: ₹ 0.00",15,green,true); preview.setPadding(0,dp(8),0,dp(10)); box.addView(preview); TextWatcherImpl tw=new TextWatcherImpl(sale,exp,preview); sale.addTextChangedListener(tw); exp.addTextChangedListener(tw); AlertDialog dlg=new AlertDialog.Builder(this).setTitle("Add Sale").setView(box).setNegativeButton("Cancel",null).setPositiveButton("Save",null).create(); dlg.setOnShowListener(x->dlg.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{ double s=num(sale),e=num(exp); if(s<=0){sale.setError("Enter sale amount");return;} if(e<0){exp.setError("Invalid amount");return;} db.add(s,e); dlg.dismiss(); refresh(); });); dlg.getWindow(); dlg.show(); }
    double num(EditText e){ try{return Double.parseDouble(e.getText().toString().trim());}catch(Exception x){return 0;} }
    class TextWatcherImpl implements android.text.TextWatcher{ EditText a,b; TextView p; TextWatcherImpl(EditText x,EditText y,TextView z){a=x;b=y;p=z;} public void beforeTextChanged(CharSequence s,int st,int c,int af){} public void onTextChanged(CharSequence s,int st,int before,int count){p.setText("Profit: "+money(num(a)-num(b)));} public void afterTextChanged(android.text.Editable e){} }
}
